spring.application.name=spring_todo_project

spring.security.user.name=user
spring.security.user.password=1234

spring.thymeleaf.prefix=classpath:/templates/
 spring.thymeleaf.suffix=.html


spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.url=jdbc:mysql://localhost:3306/example

server.port=9092

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true